project:
  type: website

website:
  title: "To Center the Margins"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About us
      - href: archive.qmd
        text: Archive
    right:
      - icon: github
        href: https://github.com/centerthemargins
  body-footer: |
    The contents of this website is available for re-use under a
    [Creative Commons Attribution 4.0 International Licence](https://creativecommons.org/licenses/by/4.0/).
  open-graph:
    locale: en_GB
    site-name: "To Center the Margins"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
